module.exports = {
  // 'Afghanistan': 'Afghanistan',
  // 'Albania': 'Albania',
  // 'Algeria': 'Algeria',
  // 'Angola': 'Angola',
  // 'Argentina': 'Argentina',
  // 'Armenia': 'Armenia',
  // 'Australia': 'Australia',
  // 'Austria': 'Austria',
  // 'Azerbaijan': 'Azerbaijan',
  // 'Bangladesh': 'Bangladesh',
  // 'Belarus': 'Belarus',
  // 'Belgium': 'Belgium',
  // 'Belize': 'Belize',
  // 'Benin': 'Benin',
  // 'Bermuda': 'Bermuda',
  // 'Bhutan': 'Bhutan',
  // 'Bolivia': 'Bolivia',
  // 'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  // 'Botswana': 'Botswana',
  // 'Brazil': 'Brazil',
  // 'Brunei': 'Brunei',
  // 'Bulgaria': 'Bulgaria',
  // 'Burkina Faso': 'Burkina Faso',
  // 'Burundi': 'Burundi',
  // 'Cambodia': 'Cambodia',
  // 'Cameroon': 'Cameroon',
  // 'Canada': 'Canada',
  // 'Central African Republic': 'Central African Republic',
  // 'Chad': 'Chad',
  // 'Chile': 'Chile',
  'china': 'China',
  '中国': 'China',
  // 'Colombia': 'Colombia',
  // 'Costa Rica': 'Costa Rica',
  // 'Croatia': 'Croatia',
  // 'Cuba': 'Cuba',
  // 'Cyprus': 'Cyprus',
  // 'Czech Republic': 'Czech Republic',
  'Republic of the Congo': 'Democratic Republic of the Congo',
  // 'Denmark': 'Denmark',
  // 'Djibouti': 'Djibouti',
  // 'Dominican Republic': 'Dominican Republic',
  // 'East Timor': 'East Timor',
  // 'Ecuador': 'Ecuador',
  // 'Egypt': 'Egypt',
  // 'El Salvador': 'El Salvador',
  // 'Equatorial Guinea': 'Equatorial Guinea',
  // 'Eritrea': 'Eritrea',
  // 'Estonia': 'Estonia',
  // 'Ethiopia': 'Ethiopia',
  // 'Falkland Islands': 'Falkland Islands',
  // 'Fiji': 'Fiji',
  // 'Finland': 'Finland',
  // 'France': 'France',
  // 'French Guiana': 'French Guiana',
  'French Southern Territories': 'French Southern and Antarctic Lands',
  // 'Gabon': 'Gabon',
  // 'Gambia': 'Gambia',
  // 'Georgia': 'Georgia',
  // 'Germany': 'Germany',
  // 'Ghana': 'Ghana',
  // 'Greece': 'Greece',
  // 'Greenland': 'Greenland',
  // 'Guatemala': 'Guatemala',
  // 'Guinea': 'Guinea',
  'Guinea-Bissau': 'Guinea Bissau',
  // 'Guyana': 'Guyana',
  // 'Haiti': 'Haiti',
  // 'Honduras': 'Honduras',
  // 'Hungary': 'Hungary',
  // 'Iceland': 'Iceland',
  // 'India': 'India',
  // 'Indonesia': 'Indonesia',
  // 'Iran': 'Iran',
  // 'Iraq': 'Iraq',
  // 'Ireland': 'Ireland',
  // 'Israel': 'Israel',
  // 'Italy': 'Italy',
  // 'Ivory Coast': 'Ivory Coast',
  // 'Jamaica': 'Jamaica',
  // 'Japan': 'Japan',
  'Jordan': 'Jordan',
  // 'Kazakhstan': 'Kazakhstan',
  // 'Kenya': 'Kenya',
  // 'Kosovo': 'Kosovo',
  // 'Kuwait': 'Kuwait',
  // 'Kyrgyzstan': 'Kyrgyzstan',
  // 'Laos': 'Laos',
  // 'Latvia': 'Latvia',
  // 'Lebanon': 'Lebanon',
  // 'Lesotho': 'Lesotho',
  // 'Liberia': 'Liberia',
  // 'Libya': 'Libya',
  'Republic of Lithuania': 'Lithuania',
  // 'Luxembourg': 'Luxembourg',
  // 'Macedonia': 'Macedonia',
  // 'Madagascar': 'Madagascar',
  // 'Malawi': 'Malawi',
  // 'Malaysia': 'Malaysia',
  // 'Mali': 'Mali',
  // 'Mauritania': 'Mauritania',
  // 'Mexico': 'Mexico',
  'Republic of Moldova': 'Moldova',
  // 'Mongolia': 'Mongolia',
  // 'Montenegro': 'Montenegro',
  // 'Morocco': 'Morocco',
  // 'Mozambique': 'Mozambique',
  'Myanmar [Burma]': 'Myanmar',
  // 'Namibia': 'Namibia',
  // 'Nepal': 'Nepal',
  // 'Netherlands': 'Netherlands',
  // 'New Caledonia': 'New Caledonia',
  // 'New Zealand': 'New Zealand',
  // 'Nicaragua': 'Nicaragua',
  // 'Niger': 'Niger',
  // 'Nigeria': 'Nigeria',
  // 'North Korea': 'North Korea',
  'Cyprus': 'Northern Cyprus',
  // 'Norway': 'Norway',
  // 'Oman': 'Oman',
  // 'Pakistan': 'Pakistan',
  // 'Panama': 'Panama',
  // 'Papua New Guinea': 'Papua New Guinea',
  // 'Paraguay': 'Paraguay',
  // 'Peru': 'Peru',
  // 'Philippines': 'Philippines',
  // 'Poland': 'Poland',
  // 'Portugal': 'Portugal',
  // 'Puerto Rico': 'Puerto Rico',
  // 'Qatar': 'Qatar',
  'Serbia': 'Republic of Serbia',
  // 'Republic of the Congo': 'Republic of the Congo',
  // 'Romania': 'Romania',
  // 'Russia': 'Russia',
  // 'Rwanda': 'Rwanda',
  // 'Saudi Arabia': 'Saudi Arabia',
  // 'Senegal': 'Senegal',
  // 'Sierra Leone': 'Sierra Leone',
  'Slovak Republic': 'Slovakia',
  // 'Slovenia': 'Slovenia',
  // 'Solomon Islands': 'Solomon Islands',
  // 'Somalia': 'Somalia',
  'Somalia': 'Somaliland',
  // 'South Africa': 'South Africa',
  'Republic of Korea': 'South Korea',
  // 'South Sudan': 'South Sudan',
  // 'Spain': 'Spain',
  // 'Sri Lanka': 'Sri Lanka',
  // 'Sudan': 'Sudan',
  // 'Suriname': 'Suriname',
  // 'Swaziland': 'Swaziland',
  // 'Sweden': 'Sweden',
  // 'Switzerland': 'Switzerland',
  // 'Syria': 'Syria',
  // 'Tajikistan': 'Tajikistan',
  // 'Thailand': 'Thailand',
  'Bahamas': 'The Bahamas',
  // 'Togo': 'Togo',
  // 'Trinidad and Tobago': 'Trinidad and Tobago',
  // 'Tunisia': 'Tunisia',
  // 'Turkey': 'Turkey',
  // 'Turkmenistan': 'Turkmenistan',
  // 'Uganda': 'Uganda',
  // 'Ukraine': 'Ukraine',
  // 'United Arab Emirates': 'United Arab Emirates',
  // 'United Kingdom': 'United Kingdom',
  'Tanzania': 'United Republic of Tanzania',
  'United States': 'United States of America'
  // 'Uruguay': 'Uruguay',
  // 'Uzbekistan': 'Uzbekistan',
  // 'Vanuatu': 'Vanuatu',
  // 'Venezuela': 'Venezuela',
  // 'Vietnam': 'Vietnam',
  // '': 'West Bank',
  // '': 'Western Sahara',
  // 'Yemen': 'Yemen',
  // 'Zambia': 'Zambia',
  // 'Zimbabwe': 'Zimbabwe'
}
